import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';
import type { Discovery, DiscoverySource } from '@cybercves/core';

/**
 * Discovery attribution as version-controlled data.
 *
 * The same principle as the product taxonomy: what a vendor found out about its
 * own bugs is *data*, reviewed and committed, not something a build step
 * rediscovers by scraping a website at deploy time. Three things follow from
 * that, and they are the whole reason this file exists:
 *
 *   1. A rebuild is deterministic. CI reads this file and never touches
 *      fortiguard.com, so a deploy cannot be broken — or worse, silently
 *      stripped of Fortinet's attribution — by their site being slow, blocking
 *      us, or changing its markup.
 *   2. The claim is auditable. Every row carries the advisory it came from and
 *      the vendor's own acknowledgement text, so a reader who doubts the
 *      internal-vs-external split can check it against the source without
 *      running anything.
 *   3. Changes are reviewable. A vendor's self-found rate moving is a diff in a
 *      pull request, not a number that quietly shifted overnight.
 *
 * Node-only (uses node:fs), so it lives under node/ like the config loader.
 */

export interface DiscoveryRecord {
  discovery: Discovery;
  source: DiscoverySource;
  /** Vendor advisory this came from, so the claim can be checked at source. */
  advisory?: string;
  /** The vendor's own acknowledgement text, verbatim. */
  credit?: string;
}

/**
 * An advisory that was read and had nothing to say.
 *
 * Recorded so a refresh job stops asking. Some advisories are withdrawn and
 * serve an empty page forever — without this, an hourly job re-fetches them
 * every hour for the life of the project, which is both rude to the origin and
 * indistinguishable from progress in the logs.
 *
 * Deliberately not permanent: `lastChecked` ages out, so an advisory that is
 * published late still gets picked up. Suppression here is a backoff, not a
 * blocklist.
 */
export interface UnresolvedRecord {
  advisory?: string;
  lastChecked: string;
  attempts: number;
}

export interface DiscoveryFile {
  vendor: string;
  generated: string;
  cves: Record<string, DiscoveryRecord>;
  unresolved?: Record<string, UnresolvedRecord>;
}

const HEADER = `# Discovery attribution — who found each vulnerability.
#
# GENERATED by \`npm run discovery\`, then committed on purpose. Do not hand-edit
# casually; do review the diff. CI applies this file with \`npm run discovery:apply\`
# and never scrapes, so what is written here is what the site publishes.
#
# "unresolved" lists advisories that were read and carried no attribution — often
# withdrawn pages. They are retried on a slow backoff rather than every run.
#
# discovery: INTERNAL (the vendor's own team) | EXTERNAL | USER | UNKNOWN
# source:    psirt-field          — the vendor's labelled "Discovered" value
#            psirt-acknowledgement — our classification of their credit prose
#            cna-source            — the CVE record's own field
`;

export function readDiscoveryFile(path: string): DiscoveryFile | null {
  let raw: string;
  try {
    raw = readFileSync(path, 'utf8');
  } catch {
    return null;
  }
  const parsed = parseYaml(raw) as Partial<DiscoveryFile> | null;
  if (!parsed?.cves) return null;
  return {
    vendor: parsed.vendor ?? 'unknown',
    generated: parsed.generated ?? '',
    cves: parsed.cves,
    unresolved: parsed.unresolved ?? {},
  };
}

/**
 * Merge new findings into the file and write it back.
 *
 * **Merge, never replace.** A scrape that covered 40 of 350 advisories — because
 * it was resumed, rate-limited, or scoped to one year — must not delete the
 * other 310. Dropping them would not read as "we lost data", it would read as
 * "Fortinet stopped disclosing", which is a false statement about a named
 * company and exactly the failure this whole subsystem is built to avoid.
 *
 * Returns what changed, so a run can say whether it learned anything new rather
 * than just reporting that it finished.
 */
export function mergeDiscoveryFile(
  path: string,
  vendor: string,
  incoming: Record<string, DiscoveryRecord>,
  now = new Date(),
  /** Advisories read this run that yielded nothing — see UnresolvedRecord. */
  unresolvedNow: ReadonlyArray<{ cveId: string; advisory?: string }> = [],
): { added: number; changed: number; unchanged: number; total: number; unresolved: number } {
  const existing = readDiscoveryFile(path);
  const cves: Record<string, DiscoveryRecord> = { ...(existing?.cves ?? {}) };
  const unresolved: Record<string, UnresolvedRecord> = { ...(existing?.unresolved ?? {}) };

  let added = 0;
  let changed = 0;
  let unchanged = 0;

  for (const [cveId, record] of Object.entries(incoming)) {
    const before = cves[cveId];
    if (!before) {
      added++;
    } else if (before.discovery !== record.discovery || before.source !== record.source) {
      changed++;
    } else {
      unchanged++;
    }
    cves[cveId] = record;
    // It answered — stop counting it against the backoff.
    delete unresolved[cveId];
  }

  for (const { cveId, advisory } of unresolvedNow) {
    if (cves[cveId]) continue;
    const prior = unresolved[cveId];
    unresolved[cveId] = {
      ...(advisory ? { advisory } : {}),
      lastChecked: now.toISOString(),
      attempts: (prior?.attempts ?? 0) + 1,
    };
  }

  // Sorted so the diff of a re-scrape shows what actually changed rather than a
  // reshuffle of 350 unrelated lines.
  const sorted: Record<string, DiscoveryRecord> = {};
  for (const key of Object.keys(cves).sort()) sorted[key] = cves[key] as DiscoveryRecord;
  const sortedUnresolved: Record<string, UnresolvedRecord> = {};
  for (const key of Object.keys(unresolved).sort())
    sortedUnresolved[key] = unresolved[key] as UnresolvedRecord;

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(
    path,
    `${HEADER}\n${stringifyYaml(
      {
        vendor,
        generated: now.toISOString(),
        cves: sorted,
        ...(Object.keys(sortedUnresolved).length ? { unresolved: sortedUnresolved } : {}),
      },
      { lineWidth: 100 },
    )}`,
  );

  return {
    added,
    changed,
    unchanged,
    total: Object.keys(sorted).length,
    unresolved: Object.keys(sortedUnresolved).length,
  };
}
