import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';
import type { Discovery, DiscoverySource } from '@cybercves/core';

/**
 * Discovery attribution as version-controlled data.
 *
 * The same principle as the product taxonomy: what a vendor found out about its
 * own bugs is *data*, reviewed and committed, not something a build step
 * rediscovers by scraping a website at deploy time. Three things follow from
 * that, and they are the whole reason this file exists:
 *
 *   1. A rebuild is deterministic. CI reads this file and never touches
 *      fortiguard.com, so a deploy cannot be broken — or worse, silently
 *      stripped of Fortinet's attribution — by their site being slow, blocking
 *      us, or changing its markup.
 *   2. The claim is auditable. Every row carries the advisory it came from and
 *      the vendor's own acknowledgement text, so a reader who doubts the
 *      internal-vs-external split can check it against the source without
 *      running anything.
 *   3. Changes are reviewable. A vendor's self-found rate moving is a diff in a
 *      pull request, not a number that quietly shifted overnight.
 *
 * Node-only (uses node:fs), so it lives under node/ like the config loader.
 */

export interface DiscoveryRecord {
  discovery: Discovery;
  source: DiscoverySource;
  /** Vendor advisory this came from, so the claim can be checked at source. */
  advisory?: string;
  /** The vendor's own acknowledgement text, verbatim. */
  credit?: string;
}

export interface DiscoveryFile {
  vendor: string;
  generated: string;
  cves: Record<string, DiscoveryRecord>;
}

const HEADER = `# Discovery attribution — who found each vulnerability.
#
# GENERATED by \`npm run discovery\`, then committed on purpose. Do not hand-edit
# casually; do review the diff. CI applies this file with \`npm run discovery:apply\`
# and never scrapes, so what is written here is what the site publishes.
#
# discovery: INTERNAL (the vendor's own team) | EXTERNAL | USER | UNKNOWN
# source:    psirt-field          — the vendor's labelled "Discovered" value
#            psirt-acknowledgement — our classification of their credit prose
#            cna-source            — the CVE record's own field
`;

export function readDiscoveryFile(path: string): DiscoveryFile | null {
  let raw: string;
  try {
    raw = readFileSync(path, 'utf8');
  } catch {
    return null;
  }
  const parsed = parseYaml(raw) as Partial<DiscoveryFile> | null;
  if (!parsed?.cves) return null;
  return {
    vendor: parsed.vendor ?? 'unknown',
    generated: parsed.generated ?? '',
    cves: parsed.cves,
  };
}

/**
 * Merge new findings into the file and write it back.
 *
 * **Merge, never replace.** A scrape that covered 40 of 350 advisories — because
 * it was resumed, rate-limited, or scoped to one year — must not delete the
 * other 310. Dropping them would not read as "we lost data", it would read as
 * "Fortinet stopped disclosing", which is a false statement about a named
 * company and exactly the failure this whole subsystem is built to avoid.
 *
 * Returns what changed, so a run can say whether it learned anything new rather
 * than just reporting that it finished.
 */
export function mergeDiscoveryFile(
  path: string,
  vendor: string,
  incoming: Record<string, DiscoveryRecord>,
  now = new Date(),
): { added: number; changed: number; unchanged: number; total: number } {
  const existing = readDiscoveryFile(path);
  const cves: Record<string, DiscoveryRecord> = { ...(existing?.cves ?? {}) };

  let added = 0;
  let changed = 0;
  let unchanged = 0;

  for (const [cveId, record] of Object.entries(incoming)) {
    const before = cves[cveId];
    if (!before) {
      added++;
    } else if (before.discovery !== record.discovery || before.source !== record.source) {
      changed++;
    } else {
      unchanged++;
    }
    cves[cveId] = record;
  }

  // Sorted so the diff of a re-scrape shows what actually changed rather than a
  // reshuffle of 350 unrelated lines.
  const sorted: Record<string, DiscoveryRecord> = {};
  for (const key of Object.keys(cves).sort()) sorted[key] = cves[key] as DiscoveryRecord;

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(
    path,
    `${HEADER}\n${stringifyYaml(
      { vendor, generated: now.toISOString(), cves: sorted },
      { lineWidth: 100 },
    )}`,
  );

  return { added, changed, unchanged, total: Object.keys(sorted).length };
}
